name: cell_segmentation
channels:
  - defaults
  - conda-forge
  - pytorch 
dependencies:
  - python=3.9 # Você pode mudar para 3.10 ou 3.11 se preferir uma versão mais recente
  - pandas
  - numpy
  - streamlit
  - ultralytics
  - matplotlib
  - tqdm
  - pyyaml
  - pathlib2
  - gradio
  - scikit-learn
  - pillow
  - gdown
  - opencv
  - pytorch 
  - torchvision 
  - torchaudio
  - plotly 
  - altair 